### ISSUE TITLE
Typo on README

### ISSUE THREAD

**Issue by ddbuscombe** [NeptuneProjects/BathyReq#1]
Thanks for making this! Very useful tool!

Just a quick (probably annoying) note that the README has a typo. It should read `req.get_point` instead of `req.get_points` - thanks!

**Comment by NeptuneProjects** [comment]
The method used to be named `get_points`, but for the life of me I can't remember why I deliberately changed it. I'll do some testing of the functionality to see if this is what was intended, or if it's a typo. Either way, thanks for pointing out the discrepancy!

**Comment by NeptuneProjects** [comment]
Confirmed the method is indeed for a single point, so the README was indeed a typo. In the process of checking the behavior, I found a bug and clarified the documentation. Thanks again!
